<a href="https://colab.research.google.com/github/afroman32/DS-Unit-2-Applied-Modeling/blob/master/module2-wrangle-ml-datasets/wrangle-ml-datasets-assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

In [0]:
movies = pd.read_csv('https://raw.githubusercontent.com/afroman32/Unit-2-Build/master/movies.csv',
                     encoding = "ISO-8859-1")

In [3]:
print(movies.shape)
movies.head()

(6820, 15)


budget                                 company  ...         writer  year
0   8000000.0           Columbia Pictures Corporation  ...   Stephen King  1986
1   6000000.0                      Paramount Pictures  ...    John Hughes  1986
2  15000000.0                      Paramount Pictures  ...       Jim Cash  1986
3  18500000.0  Twentieth Century Fox Film Corporation  ...  James Cameron  1986
4   9000000.0                    Walt Disney Pictures  ...  Mark H. Baker  1986

[5 rows x 15 columns]

In [4]:
movies['score'].describe()

count    6820.000000
mean        6.374897
std         1.003142
min         1.500000
25%         5.800000
50%         6.400000
75%         7.100000
max         9.300000
Name: score, dtype: float64

In [0]:
# director track record, movies success by director
# create new target based off of gross revenue and score
# make sure to train on features that would come before the target

In [6]:
movies['gross'].describe()

count    6.820000e+03
mean     3.349783e+07
std      5.819760e+07
min      7.000000e+01
25%      1.515839e+06
50%      1.213568e+07
75%      4.006534e+07
max      9.366622e+08
Name: gross, dtype: float64

In [0]:
gross_rate = []
for i in range(len(movies['gross'])):
  if movies['gross'][i]<=1.515839e+06:
    gross_rate.append(1)
  elif movies['gross'][i]<=1.213568e+07 and movies['gross'][i]>1.515839e+06:
    gross_rate.append(2)
  elif movies['gross'][i]<=4.006534e+07 and movies['gross'][i]>1.213568e+07:
    gross_rate.append(3)
  else:
    gross_rate.append(4)
gross_rate = np.array(gross_rate)

In [8]:
len(gross_rate)

6820

In [9]:
type(gross_rate)

numpy.ndarray

In [10]:
gross_rate[:10]

array([4, 4, 4, 4, 3, 4, 3, 2, 4, 4])

In [11]:
movies['gross'].head(10)

0     52287414.0
1     70136369.0
2    179800601.0
3     85160248.0
4     18564613.0
5    138530565.0
6     12729917.0
7      8551228.0
8     40471663.0
9     40456565.0
Name: gross, dtype: float64

In [0]:
 score_rate = np.array([])
for i in range(len(movies['score'])):
  if movies['score'][i]<=2.5:
    score_rate = np.append(score_rate, 1)
  elif movies['score'][i]<=5 and movies['gross'][i]>2.5:
    score_rate = np.append(score_rate, 2)
  elif movies['score'][i]<=7.5 and movies['gross'][i]>5:
    score_rate = np.append(score_rate, 3)
  else:
    score_rate = np.append(score_rate, 4)

In [13]:
len(score_rate)

6820

In [14]:
score_rate

array([4., 4., 3., ..., 3., 3., 3.])

In [15]:
movies['score'].head(10)

0    8.1
1    7.8
2    6.9
3    8.4
4    6.9
5    8.1
6    7.4
7    7.8
8    6.8
9    7.5
Name: score, dtype: float64

In [16]:
rate = (gross_rate + score_rate)/2
rate

array([4. , 4. , 3.5, ..., 2.5, 2. , 2. ])

In [17]:
movies['success_rate'] = rate
movies['success_rate'].value_counts(normalize = True)

2.5    0.247067
3.0    0.243255
2.0    0.229912
3.5    0.215982
4.0    0.039736
1.5    0.023021
1.0    0.001026
Name: success_rate, dtype: float64

In [18]:
movies['success_rate'].nunique()

7

#Train, Val, Test Split 
(60,20,20)

In [0]:
movies.sort_values(by = 'released', inplace = True)

In [20]:
movies.head()

budget             company  ...  year success_rate
96         0.0  New World Pictures  ...  1986          2.5
195        0.0            Longshot  ...  1986          2.0
47   1100000.0     Empire Pictures  ...  1986          2.0
27         0.0    TriStar Pictures  ...  1986          3.0
218        0.0   DIC Entertainment  ...  1986          2.5

[5 rows x 16 columns]

In [0]:
movies.reset_index(inplace = True, drop  = True)

In [22]:
movies.head()

budget             company country  ...             writer  year  success_rate
0        0.0  New World Pictures     USA  ...     John Carpenter  1986           2.5
1        0.0            Longshot     USA  ...         Tim Conway  1986           2.0
2  1100000.0     Empire Pictures     USA  ...            Ed Naha  1986           2.0
3        0.0    TriStar Pictures     USA  ...  Kevin Alyn Elders  1986           3.0
4        0.0   DIC Entertainment  Canada  ...      George Gately  1986           2.5

[5 rows x 16 columns]

In [23]:
no_budg = movies[movies['budget']==0]
no_budg.shape

(2182, 16)

In [0]:
# set end year for training data set
train_lim = movies['year'].min()+19

# set beginning year for test data
test_lim = movies['year'].max()-4

In [0]:
# movies in years less than training end year
train = movies[movies['year']<= train_lim]

# all movies in years greater than training end year
val_temp = movies[movies['year'] > train_lim]

# movies in years less than test year and greater than training end year
val = val_temp[val_temp['year'] < test_lim]

# movies in years greater than test year
test = movies[movies['year']>=test_lim]

In [26]:
train.shape, val.shape, test.shape

((4400, 16), (1320, 16), (1100, 16))

In [27]:
movies['success_rate'].value_counts(normalize=True)

2.5    0.247067
3.0    0.243255
2.0    0.229912
3.5    0.215982
4.0    0.039736
1.5    0.023021
1.0    0.001026
Name: success_rate, dtype: float64

#Assignment 1

##Baseline

In [28]:
from sklearn.metrics import mean_absolute_error

train['gross'].mean()

y_train = train['gross']
y_test = test['gross']
base_guess = y_train.mean()


# test error
y_base_pred = [base_guess] * len(y_test)
mae_test = mean_absolute_error(y_test, y_base_pred)

print(f'Mean Absolute Error: ${mae_test:,.2f}')

Mean Absolute Error: $45,726,662.13


##Basic Model

In [0]:
# set target
target = 'gross'

# set features
features = ['budget', 'genre', 'rating', 'year']

# set X matrices and y vectors
X_train = train[features]
y_train = train[target]

X_val = val[features]
y_val = val[target]

X_test = test[features]
y_test = test[target]

In [30]:
!pip install category_encoders==2.*

In [31]:
X_train.head()

budget   genre rating  year
0        0.0  Action      R  1986
1        0.0  Comedy  PG-13  1986
2  1100000.0  Comedy  PG-13  1986
3        0.0  Action  PG-13  1986
4        0.0  Family      G  1986

In [32]:
import category_encoders as ce
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.pipeline import make_pipeline
# from math import sqrt

pipeline = make_pipeline(
    ce.OrdinalEncoder(),
    # SimpleImputer(strategy = 'mean'),
    StandardScaler(),
    LinearRegression()
)

# Fit on training set
pipeline.fit(X_train, y_train)

# make predictions
y_pred = pipeline.predict(X_test)

# test mean absolute error
mae = mean_absolute_error(y_test, y_pred)
print(f'Test Mean Absolute Error: {mae:,.2f}')

Test Mean Absolute Error: 28,700,487.17
